name: CI Pipeline

on:
  push:
    branches:
      - "main"
      - "dev"
  create:
    tags:
      - "*"
  pull_request:
    branches:
      - "main"
      - "dev"

permissions:
  contents: read
  packages: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - platform: linux/amd64
            base: distroless
            runs-on: ubuntu-24.04
            use-qemu: false
          - platform: linux/arm/v6
            base: alpine
            runs-on: ubuntu-22.04-arm
            use-qemu: true
          - platform: linux/arm/v7
            base: alpine
            runs-on: ubuntu-22.04-arm
            use-qemu: true
          - platform: linux/arm64
            base: distroless
            runs-on: ubuntu-24.04-arm
            use-qemu: false
    uses: ./.github/workflows/build-image.yml
    with:
      registry: ghcr.io
      platform: ${{ matrix.config.platform }}
      base: ${{ matrix.config.base }}
      runs-on: ${{ matrix.config.runs-on }}
      use-qemu: ${{ matrix.config.use-qemu }}
      context: .
      dockerfile: ./Dockerfile
      image-suffix: ""
      digest-prefix: "digests-base-"

  merge:
    if: github.event_name != 'pull_request'
    needs:
      - build
    uses: ./.github/workflows/merge-manifests.yml
    with:
      registry: ghcr.io
      image-suffix: ""
      digest-prefix: "digests-base-"

  lint:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install pyflakes
        run: |
          python -m pip install --upgrade pip
          pip install pyflakes
      - name: Run pyflakes
        run: |
          pyflakes ./*.py
